name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build twine
    
    - name: Build package
      run: python -m build
    
    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: dist/*
        generate_release_notes: true
        body: |
          ## Claude Code Project Template ${{ github.ref_name }}
          
          ### What's New
          See the full changelog below for all changes.
          
          ### Installation
          ```bash
          git clone https://github.com/dbankscard/claude-code-project-template.git
          cd claude-code-project-template
          python scripts/initialize_project.py my-project
          ```
          
          ### Documentation
          - [Getting Started](https://github.com/dbankscard/claude-code-project-template/blob/main/docs/guides/getting-started.md)
          - [Usage Guide](https://github.com/dbankscard/claude-code-project-template/blob/main/docs/guides/usage.md)
          - [Customization](https://github.com/dbankscard/claude-code-project-template/blob/main/docs/guides/customization.md)