name: Test Template

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
    
    - name: Lint with ruff
      run: |
        ruff check scripts/ tests/
    
    - name: Format with black
      run: |
        black --check scripts/ tests/
    
    - name: Type check with mypy
      run: |
        mypy scripts/
    
    - name: Test with pytest
      run: |
        pytest tests/ -v --cov=scripts --cov-report=xml
    
    - name: Test template initialization
      run: |
        python scripts/initialize_project.py test-project --dry-run
    
    - name: Validate sub-agent configurations
      run: |
        python tests/test_agents.py
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
