name: Validate Agents

on:
  push:
    paths:
      - 'template/.claude/agents/**'
      - 'template/.claude/commands/**'
  pull_request:
    paths:
      - 'template/.claude/agents/**' 
      - 'template/.claude/commands/**'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e ".[dev]"
        pip install pyyaml
    
    - name: Validate agent and command definitions
      run: |
        echo "Running comprehensive validation tests..."
        python -m pytest tests/test_agents.py tests/test_commands.py -v