name: Validate Agents

on:
  push:
    branches: [ main ]
    paths:
      - 'template/.claude/agents/**'
      - 'template/.claude/commands/**'
      - '.github/workflows/validate-agents.yml'
      - 'tests/test_agents.py'
      - 'tests/test_commands.py'
  pull_request:
    paths:
      - 'template/.claude/agents/**' 
      - 'template/.claude/commands/**'
      - '.github/workflows/validate-agents.yml'
      - 'tests/test_agents.py'
      - 'tests/test_commands.py'

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pytest-cov pyyaml
    
    - name: Validate agent and command definitions
      run: |
        echo "Running comprehensive validation tests..."
        python -m pytest tests/test_agents.py tests/test_commands.py -v